spring.datasource.url=jdbc:mysql://localhost:3306/dazzling_blog
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
# spring.thymeleaf.prefix=classpath:/templates/
spring.security.user.role=Admin
spring.servlet.multipart.max-file-size=4096KB
spring.servlet.multipart.max-request-size=4096KB
server.tomcat.remote_ip_header=x-forwarded-for
server.tomcat.protocol_header=x-forwarded-proto
server.tomcat.port-header=X-Forwarded-Port
server.use-forward-headers=true
server.address=0.0.0.0
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
file.upload.avatarPath=blog/images/avatars/
file.upload.coverPath=blog/images/covers/
file.upload.path=blog/resources/
# file.upload.path=/home/www/resources/static/blog/images/
logging.file.path=logs
logging.file.name=logs/blog.log
logging.level.root=INFO
logging.level.com.dazzling.blog=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.csrf=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n